### ISSUE TITLE
[General] Create Documentation pages

### ISSUE THREAD

**Issue by peoplenarthax** [peoplenarthax/chromosome-js#4]
In order to start adding documentation to the project we should have a easy way of generatic this documentation directly from the repository. 

Maybe using [GatsbyJS](https://www.gatsbyjs.org/) seems like a good idea, then we could create a github page.

**Comment by vektorious** [comment]
Just something else I want to throw in is [Jekyll](https://jekyllrb.com/). I use it for my [personal website](https://alexanderkutschera.com/) which I host on GitHub and I think is very easy to use (in combination with gulp)

**Comment by peoplenarthax** [comment]
Forgot to read this. Jekyll seems powerful, but the point that it is base on ruby push me backwards, since this is a JavaScript project I expect most of the people that contribute with some code to be able to work better with JS than Ruby. Otherwise it is simple than Gatsby.

But in anyway, if you could create a branch with an example in how the documentation directory will look and how to use Jekyll, maybe is easy to decide than by looking at the documentation of Jekyll.

**Comment by peoplenarthax** [comment]
Actually, docsify seems like a better option. Simpler and you only need to add markdown
